CREATE TABLE IF NOT EXISTS employee (
    id SERIAL NOT NULL PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100),
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    createdOn TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    lastUpdatedOn TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS timesheet_template (
    id SERIAL NOT NULL PRIMARY KEY,
    templateDay VARCHAR(10) NOT NULL,
    currentDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    checkIn TIME NOT NULL,
    checkOut TIME NOT NULL,
    lunchBreakStart TIME NOT NULL,
    lunchBreakEnd TIME NOT NULL
)